authors:
- Iván Hidalgo-Cenalmor
- Estibaliz Gómez-de-Mariscal
cite:
- doi: https://doi.org/10.1101/2023.11.19.567606
  text: 'Iván Hidalgo-Cenalmor, Joanna W. Pylvänäinen, Mariana G Ferreira, et al., DL4MicEverywhere: Deep learning for microscopy made flexible, shareable, and reproducible, bioRxiv 2023'
config:
  dl4miceverywhere:
    cuda_version: 11.2.2
    cudnn_version: 8.1.1.33
    description: Notebook to threshold images
    dl4miceverywhere_version: 2.1.0
    docker_hub_image: 
    notebook_url: MyCoolNotebook.ipynb
    notebook_version: 0.1.0
    python_version: '3.9'
    requirements_url: requirements.txt
    sections_to_remove: 2.
    ubuntu_version: '20.04'
description: Notebook to threshold images
format_version: 0.5.3
git_repo: https://github.com/IvanHCenalmor/DL4MicEverywhere_Example
links:
- Notebook Preview
name: Threshold notebook
tags:
- colab
- notebook
- dl4miceverywhere
- threshold
type: application
version: 1.4.0
